import type { ToolSearchMeta } from "./search-index";

export const catalogSearchMeta: Record<string, ToolSearchMeta> = {
  argocd: { slug: "argocd", simpleTitle: "Deploy to Kubernetes from Git (GitOps)", keywords: ["gitops", "continuous delivery", "argo cd", "sync kubernetes", "deploy from git"], level: "advanced" },
  flux: { slug: "flux", simpleTitle: "Sync Kubernetes from Git automatically", keywords: ["gitops", "fluxcd", "git sync", "kustomization", "helm release"], level: "advanced" },
  tekton: { slug: "tekton", simpleTitle: "Build CI/CD pipelines on Kubernetes", keywords: ["cloud native ci", "pipeline", "knative", "tkn", "build on k8s"], level: "advanced" },
  k3s: { slug: "k3s", simpleTitle: "Run lightweight Kubernetes anywhere", keywords: ["light k8s", "edge kubernetes", "rancher k3s", "small cluster"], level: "intermediate" },
  microk8s: { slug: "microk8s", simpleTitle: "Single-command Kubernetes (MicroK8s)", keywords: ["snap kubernetes", "local k8s", "canonical kubernetes"], level: "beginner" },
  kind: { slug: "kind", simpleTitle: "Run Kubernetes in Docker locally", keywords: ["kubernetes in docker", "local cluster", "dev kubernetes", "kind cluster"], level: "beginner" },
  buildah: { slug: "buildah", simpleTitle: "Build container images without Docker", keywords: ["oci image", "container build", "rootless build", "podman buildah"], level: "intermediate" },
  harbor: { slug: "harbor", simpleTitle: "Run a private Docker registry", keywords: ["container registry", "docker registry", "image scan", "private registry"], level: "intermediate" },
  portainer: { slug: "portainer", simpleTitle: "Manage Docker with a web dashboard", keywords: ["docker ui", "container dashboard", "docker gui", "manage containers"], level: "beginner" },
  rancher: { slug: "rancher", simpleTitle: "Manage multiple Kubernetes clusters", keywords: ["multi cluster", "k8s management", "rancher ui", "cluster manager"], level: "advanced" },
  istio: { slug: "istio", simpleTitle: "Add a service mesh to Kubernetes", keywords: ["service mesh", "traffic management", "mtls", "sidecar proxy", "envoy"], level: "advanced" },
  packer: { slug: "packer", simpleTitle: "Build machine images automatically", keywords: ["ami builder", "vm image", "golden image", "hashicorp packer"], level: "intermediate" },
  pulumi: { slug: "pulumi", simpleTitle: "Create cloud infrastructure with code", keywords: ["iac", "typescript terraform", "infrastructure code", "pulumi up"], level: "intermediate" },
  nomad: { slug: "nomad", simpleTitle: "Schedule containers and batch jobs", keywords: ["hashicorp nomad", "workload scheduler", "orchestrator", "nomad cluster"], level: "advanced" },
  vault: { slug: "vault", simpleTitle: "Store secrets and passwords securely", keywords: ["secrets manager", "api keys", "hashicorp vault", "password vault", "certificates"], level: "advanced" },
  falco: { slug: "falco", simpleTitle: "Detect attacks on running containers", keywords: ["runtime security", "threat detection", "container security", "intrusion detection"], level: "advanced" },
  fail2ban: { slug: "fail2ban", simpleTitle: "Block hackers trying to guess passwords", keywords: ["ban ip", "brute force", "ssh protection", "intrusion prevention"], level: "beginner" },
  traefik: { slug: "traefik", simpleTitle: "Modern reverse proxy with auto HTTPS", keywords: ["load balancer", "reverse proxy", "ingress", "lets encrypt proxy"], level: "intermediate" },
  apache: { slug: "apache", simpleTitle: "Set up Apache web server (httpd)", keywords: ["httpd", "web server", "virtual host", "host website", "apache2"], level: "beginner" },
  consul: { slug: "consul", simpleTitle: "Service discovery and health checks", keywords: ["service mesh", "key value store", "hashicorp consul", "microservices discovery"], level: "advanced" },
  squid: { slug: "squid", simpleTitle: "Set up a caching proxy server", keywords: ["forward proxy", "cache proxy", "http proxy", "squid proxy"], level: "intermediate" },
  keepalived: { slug: "keepalived", simpleTitle: "High availability with floating IP", keywords: ["vrrp", "failover ip", "ha cluster", "load balancer failover"], level: "advanced" },
  mongodb: { slug: "mongodb", simpleTitle: "Set up a MongoDB document database", keywords: ["nosql", "document db", "mongo", "json database"], level: "beginner" },
  mariadb: { slug: "mariadb", simpleTitle: "Set up MariaDB (MySQL-compatible)", keywords: ["mysql alternative", "sql database", "mariadb server"], level: "beginner" },
  rabbitmq: { slug: "rabbitmq", simpleTitle: "Message queue for async apps", keywords: ["message broker", "amqp", "queue", "microservices messaging"], level: "intermediate" },
  kafka: { slug: "kafka", simpleTitle: "Event streaming platform (Kafka)", keywords: ["event stream", "message queue", "apache kafka", "pub sub"], level: "advanced" },
  memcached: { slug: "memcached", simpleTitle: "Fast in-memory cache for apps", keywords: ["cache server", "memory cache", "session cache", "redis alternative"], level: "beginner" },
  elasticsearch: { slug: "elasticsearch", simpleTitle: "Search engine and log analytics (ELK)", keywords: ["elk stack", "log search", "elastic", "kibana logs", "full text search"], level: "intermediate" },
  loki: { slug: "loki", simpleTitle: "Collect and search logs (Grafana Loki)", keywords: ["log aggregation", "grafana logs", "prometheus logs", "log monitoring"], level: "intermediate" },
  jaeger: { slug: "jaeger", simpleTitle: "Trace requests across microservices", keywords: ["distributed tracing", "apm", "opentelemetry traces", "request tracing"], level: "advanced" },
  opentelemetry: { slug: "opentelemetry", simpleTitle: "Collect traces, metrics, and logs", keywords: ["otel", "observability", "telemetry", "instrumentation"], level: "advanced" },
  netdata: { slug: "netdata", simpleTitle: "Real-time server monitoring dashboard", keywords: ["live monitoring", "server dashboard", "cpu memory graph", "watch server"], level: "beginner" },
  samba: { slug: "samba", simpleTitle: "Share files with Windows computers", keywords: ["smb", "cifs", "file share", "windows share", "network folder"], level: "intermediate" },
  postfix: { slug: "postfix", simpleTitle: "Set up an email server (Postfix)", keywords: ["mail server", "smtp", "send email", "mta", "email relay"], level: "intermediate" },
  gcloud: { slug: "gcloud", simpleTitle: "Manage Google Cloud from terminal", keywords: ["gcp", "google cloud", "gcloud sdk", "gce", "gke", "bigquery"], level: "intermediate" },
  "github-cli": { slug: "github-cli", simpleTitle: "Manage GitHub from the command line (gh)", keywords: ["gh cli", "github pr", "github repo", "gh auth"], level: "beginner" },
  doctl: { slug: "doctl", simpleTitle: "Manage DigitalOcean droplets and K8s", keywords: ["digital ocean", "doctl", "droplet", "digitalocean kubernetes"], level: "intermediate" },
  terragrunt: { slug: "terragrunt", simpleTitle: "Manage Terraform across environments", keywords: ["terraform wrapper", "terragrunt hcl", "dry terraform", "gruntwork"], level: "advanced" },
  kustomize: { slug: "kustomize", simpleTitle: "Customize Kubernetes YAML without Helm", keywords: ["kubectl kustomize", "k8s overlays", "patch yaml", "kubernetes customize"], level: "intermediate" },
  vagrant: { slug: "vagrant", simpleTitle: "Create portable development VMs", keywords: ["dev vm", "virtualbox vagrant", "vagrant up", "local vm"], level: "beginner" },
  direnv: { slug: "direnv", simpleTitle: "Auto-load env vars per project folder", keywords: ["environment variables", "envrc", "project env", "shell env"], level: "beginner" },
  circleci: { slug: "circleci", simpleTitle: "Run CI/CD builds in the cloud", keywords: ["circle ci", "circleci config", "parallel builds", "ci pipeline"], level: "beginner" },
  "drone-ci": { slug: "drone-ci", simpleTitle: "Container-native CI/CD server", keywords: ["drone io", "drone pipeline", "docker ci"], level: "intermediate" },
  buildkite: { slug: "buildkite", simpleTitle: "Self-hosted CI agents with cloud UI", keywords: ["buildkite agent", "build pipeline", "ci agent"], level: "intermediate" },
  teamcity: { slug: "teamcity", simpleTitle: "JetBrains CI/CD build server", keywords: ["jetbrains ci", "teamcity server", "build chain"], level: "intermediate" },
  "travis-ci": { slug: "travis-ci", simpleTitle: "GitHub CI with .travis.yml", keywords: ["travis yml", "travis build", "continuous integration"], level: "beginner" },
  "azure-devops": { slug: "azure-devops", simpleTitle: "Microsoft Azure DevOps Pipelines", keywords: ["azure pipelines", "az devops", "azure ci cd", "yaml pipeline"], level: "intermediate" },
  "bitbucket-pipelines": { slug: "bitbucket-pipelines", simpleTitle: "CI/CD built into Bitbucket", keywords: ["bitbucket ci", "bitbucket yaml", "atlassian pipeline"], level: "beginner" },
  datadog: { slug: "datadog", simpleTitle: "Install Datadog monitoring agent", keywords: ["datadog agent", "apm monitoring", "infrastructure monitoring", "dd agent"], level: "intermediate" },
  cloudflare: { slug: "cloudflare", simpleTitle: "Manage Cloudflare with Wrangler CLI", keywords: ["wrangler", "cloudflare workers", "cdn dns", "cloudflare cli"], level: "intermediate" },
  tmux: { slug: "tmux", simpleTitle: "Keep terminal sessions alive after SSH", keywords: ["terminal multiplexer", "tmux session", "detach ssh", "screen alternative"], level: "beginner" },
  nodejs: { slug: "nodejs", simpleTitle: "Install Node.js and npm", keywords: ["node js", "npm", "javascript server", "express node"], level: "beginner" },
  ruby: { slug: "ruby", simpleTitle: "Install Ruby and gems", keywords: ["rails", "gem install", "ruby lang", "bundler"], level: "beginner" },
  gradle: { slug: "gradle", simpleTitle: "Build Java and Kotlin projects", keywords: ["gradle build", "java build tool", "android gradle", "kotlin build"], level: "intermediate" },
  jq: { slug: "jq", simpleTitle: "Parse JSON from the command line", keywords: ["json parser", "jq filter", "api json", "cli json"], level: "beginner" },
  "pre-commit": { slug: "pre-commit", simpleTitle: "Run lint checks before every git commit", keywords: ["git hooks", "precommit", "lint commit", "code quality hooks"], level: "beginner" },
  zookeeper: { slug: "zookeeper", simpleTitle: "Coordination service for Kafka clusters", keywords: ["apache zookeeper", "zk cluster", "kafka dependency", "distributed coordination"], level: "advanced" },
  php: { slug: "php", simpleTitle: "Install PHP for web apps and Laravel", keywords: ["php fpm", "laravel", "wordpress", "composer", "php mysql"], level: "beginner" },
  openvpn: { slug: "openvpn", simpleTitle: "Set up an OpenVPN server", keywords: ["vpn server", "openvpn client", "remote access vpn", "site to site"], level: "intermediate" },
  velero: { slug: "velero", simpleTitle: "Backup and restore Kubernetes clusters", keywords: ["k8s backup", "cluster backup", "velero restore", "disaster recovery"], level: "advanced" },
  "aws-cloudformation": { slug: "aws-cloudformation", simpleTitle: "Create AWS infrastructure from templates", keywords: ["cloudformation", "cfn", "aws iac", "stack", "aws template"], level: "intermediate" },
  "aws-secrets-manager": { slug: "aws-secrets-manager", simpleTitle: "Store secrets in AWS with rotation", keywords: ["aws secrets", "password manager aws", "secret rotation", "credentials aws"], level: "intermediate" },
  "external-secrets-operator": { slug: "external-secrets-operator", simpleTitle: "Sync AWS/Vault secrets into Kubernetes", keywords: ["eso", "kubernetes secrets", "aws secrets k8s", "external secret"], level: "advanced" },
  etcd: { slug: "etcd", simpleTitle: "Distributed key-value store for Kubernetes", keywords: ["etcd cluster", "k8s state", "key value", "distributed store"], level: "advanced" },
  eureka: { slug: "eureka", simpleTitle: "Service registry for Java microservices", keywords: ["netflix eureka", "spring cloud", "service discovery", "microservices registry"], level: "intermediate" },
  kyverno: { slug: "kyverno", simpleTitle: "Kubernetes policy validation and mutation", keywords: ["k8s policy", "admission controller", "cluster policy", "kyverno policy"], level: "advanced" },
  linkerd: { slug: "linkerd", simpleTitle: "Lightweight Kubernetes service mesh", keywords: ["service mesh", "linkerd proxy", "mtls mesh", "linkerd install"], level: "advanced" },
  cilium: { slug: "cilium", simpleTitle: "eBPF networking and security for Kubernetes", keywords: ["cilium mesh", "ebpf kubernetes", "hubble", "cilium install"], level: "advanced" },
  calico: { slug: "calico", simpleTitle: "Kubernetes network policies and pod networking", keywords: ["network policy", "calico cni", "pod network", "tigera"], level: "advanced" },
  "elk-stack": { slug: "elk-stack", simpleTitle: "Elasticsearch + Logstash + Kibana log stack", keywords: ["elk", "elastic stack", "log aggregation", "logstash kibana"], level: "intermediate" },
  fluentd: { slug: "fluentd", simpleTitle: "Collect and route logs to many destinations", keywords: ["log collector", "td-agent", "fluent bit", "log forwarder"], level: "intermediate" },
  graylog: { slug: "graylog", simpleTitle: "Centralized log management and alerts", keywords: ["graylog server", "log management", "log alerts", "gelf"], level: "intermediate" },
  kibana: { slug: "kibana", simpleTitle: "Visualize and search Elasticsearch data", keywords: ["kibana dashboard", "elastic ui", "log visualization", "kibana install"], level: "intermediate" },
  splunk: { slug: "splunk", simpleTitle: "Enterprise log analytics and search", keywords: ["splunk forwarder", "splunk enterprise", "siem", "log analytics"], level: "advanced" },
  "new-relic": { slug: "new-relic", simpleTitle: "APM and infrastructure monitoring", keywords: ["newrelic agent", "apm", "application monitoring", "new relic install"], level: "intermediate" },
  logzio: { slug: "logzio", simpleTitle: "Managed ELK log shipping platform", keywords: ["logz io", "managed elk", "cloud logging", "filebeat logzio"], level: "intermediate" },
  "syslog-ng": { slug: "syslog-ng", simpleTitle: "Enterprise log collection and routing", keywords: ["syslog ng", "log routing", "syslog collector", "centralized logging"], level: "intermediate" },
  postman: { slug: "postman", simpleTitle: "Test and automate REST API requests", keywords: ["api testing", "newman", "postman collection", "rest client"], level: "beginner" },
  selenium: { slug: "selenium", simpleTitle: "Automate browser testing for web apps", keywords: ["webdriver", "browser automation", "e2e testing", "selenium python"], level: "intermediate" },
  slack: { slug: "slack", simpleTitle: "Team chat and CI/CD notifications", keywords: ["slack webhook", "slack integration", "deploy notification", "slack bot"], level: "beginner" },
  jira: { slug: "jira", simpleTitle: "Agile issue tracking and sprints", keywords: ["atlassian jira", "bug tracker", "scrum board", "jira api"], level: "beginner" },
  trello: { slug: "trello", simpleTitle: "Kanban boards for task tracking", keywords: ["trello board", "kanban", "project cards", "trello api"], level: "beginner" },
  confluence: { slug: "confluence", simpleTitle: "Team wiki and documentation", keywords: ["atlassian confluence", "runbook wiki", "documentation", "confluence api"], level: "beginner" },
  vscode: { slug: "vscode", simpleTitle: "Code editor with DevOps extensions", keywords: ["visual studio code", "vscode docker", "vscode kubernetes", "code editor"], level: "beginner" },
  "sublime-text": { slug: "sublime-text", simpleTitle: "Fast text editor for configs and scripts", keywords: ["sublime editor", "text editor", "syntax highlighting"], level: "beginner" },
  "notepad-plus-plus": { slug: "notepad-plus-plus", simpleTitle: "Windows source code editor", keywords: ["notepad++", "npp", "windows editor", "log editor"], level: "beginner" },
};

/** Plain-English search aliases → tool slugs */
export const SEARCH_ALIASES: Record<string, string[]> = {
  gitops: ["argocd", "flux"],
  "service mesh": ["istio", "linkerd", "cilium", "consul"],
  registry: ["harbor", "docker", "eureka"],
  secrets: ["vault", "aws-secrets-manager", "external-secrets-operator"],
  logs: ["loki", "elasticsearch", "elk-stack", "fluentd", "graylog", "kibana", "splunk", "syslog-ng", "logzio"],
  tracing: ["jaeger", "opentelemetry", "new-relic"],
  "message queue": ["rabbitmq", "kafka"],
  proxy: ["nginx", "traefik", "squid", "haproxy"],
  mail: ["postfix"],
  "file share": ["samba", "nfs", "ftp"],
  lightweight: ["k3s", "microk8s", "kind"],
  elk: ["elasticsearch", "elk-stack", "kibana", "grafana"],
  monitoring: ["prometheus", "grafana", "netdata", "zabbix", "nagios", "datadog", "new-relic", "splunk"],
  ci: ["jenkins", "github-actions", "gitlab-ci", "tekton", "argocd", "circleci", "travis-ci", "buildkite", "drone-ci", "teamcity", "azure-devops", "bitbucket-pipelines", "slack"],
  cd: ["argocd", "flux", "jenkins"],
  database: ["mysql", "postgresql", "mongodb", "mariadb", "redis"],
  cache: ["redis", "memcached"],
  vpn: ["wireguard", "openvpn"],
  ssl: ["certbot", "nginx"],
  gcp: ["gcloud"],
  google: ["gcloud"],
  aws: ["aws-cli", "aws-cloudformation", "aws-secrets-manager", "eksctl"],
  cloudformation: ["aws-cloudformation"],
  gh: ["github-cli"],
  terraform: ["terraform", "terragrunt", "aws-cloudformation"],
  kubernetes: ["kubernetes", "kubectl", "helm", "minikube", "k3s", "microk8s", "kind", "rancher", "kustomize", "kyverno", "calico", "cilium", "linkerd"],
  k8s: ["kubernetes", "kubectl", "helm", "argocd", "istio", "linkerd", "cilium", "calico", "kyverno", "kustomize"],
  docker: ["docker", "docker-compose", "podman", "portainer", "buildah"],
  policy: ["kyverno", "falco", "selinux"],
  editor: ["vscode", "sublime-text", "notepad-plus-plus"],
  testing: ["postman", "selenium", "sonarqube"],
  collaboration: ["slack", "jira", "trello", "confluence"],
};
