export interface Snippet {
  id: string;
  task: string;
  cmd: string;
  tags: string[];
  tool?: string;
  /** Destructive or irreversible — show safe-mode warning */
  destructive?: boolean;
  destructiveNote?: string;
}

export const snippetTags = [
  { id: "aws", label: "AWS", icon: "☁️" },
  { id: "docker", label: "Docker", icon: "🐳" },
  { id: "k8s", label: "Kubernetes", icon: "☸️" },
  { id: "terraform", label: "Terraform", icon: "🏗️" },
  { id: "nginx", label: "Nginx", icon: "🌐" },
  { id: "ci", label: "CI/CD", icon: "🔄" },
  { id: "debug", label: "Debug", icon: "🔧" },
  { id: "git", label: "Git", icon: "📦" },
  { id: "finops", label: "FinOps", icon: "💰" },
  { id: "observe", label: "Observe", icon: "📊" },
  { id: "gcp", label: "GCP", icon: "🌐" },
  { id: "azure", label: "Azure", icon: "☁️" },
  { id: "backup", label: "Backup", icon: "💾" },
] as const;

export const snippets: Snippet[] = [
  { id: "ecr-login", task: "ECR login + docker push", tags: ["aws", "docker", "ci"], cmd: `aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789.dkr.ecr.us-east-1.amazonaws.com\ndocker tag myapp:latest 123456789.dkr.ecr.us-east-1.amazonaws.com/myapp:latest\ndocker push 123456789.dkr.ecr.us-east-1.amazonaws.com/myapp:latest` },
  { id: "eks-kubeconfig", task: "Merge EKS into kubeconfig", tags: ["aws", "k8s"], cmd: `aws eks update-kubeconfig --name my-cluster --region us-east-1\nkubectl config current-context\nkubectl get nodes` },
  { id: "assume-role", task: "Assume IAM role (CLI session)", tags: ["aws"], cmd: `aws sts assume-role --role-arn arn:aws:iam::123456789012:role/DeployRole --role-session-name deploy\nexport AWS_ACCESS_KEY_ID=...\nexport AWS_SECRET_ACCESS_KEY=...\nexport AWS_SESSION_TOKEN=...\naws sts get-caller-identity` },
  { id: "caller-identity", task: "Verify AWS identity", tags: ["aws", "debug"], cmd: `aws sts get-caller-identity\naws configure list` },
  { id: "debug-pod-netshoot", task: "Debug DNS/network in pod", tags: ["k8s", "debug"], cmd: `kubectl run netshoot --rm -it --image=nicolaka/netshoot --restart=Never -n <ns> -- /bin/bash\n# inside: nslookup kubernetes.default, curl -v svc:port` },
  { id: "port-forward-svc", task: "Port-forward service locally", tags: ["k8s", "debug"], cmd: `kubectl port-forward svc/<service> 8080:80 -n <namespace>\ncurl -I http://localhost:8080` },
  { id: "helm-dry-run", task: "Helm dry-run debug", tags: ["k8s"], cmd: `helm upgrade --install myrelease ./chart -n apps -f values.yaml --dry-run --debug\nhelm template myrelease ./chart -f values.yaml | kubectl apply --dry-run=client -f -` },
  { id: "helm-rollback", task: "Helm rollback failed release", tags: ["k8s", "debug"], cmd: `helm history myrelease -n apps\nhelm rollback myrelease <revision> -n apps\nhelm status myrelease -n apps` },
  { id: "tf-force-unlock", task: "Terraform force-unlock", tags: ["terraform", "debug"], destructive: true, destructiveNote: "Confirm no other apply is running. Run in staging first — wrong unlock can corrupt state.", cmd: `terraform force-unlock <LOCK_ID>\n# LOCK_ID from error message — confirm no other apply running first` },
  { id: "tf-import", task: "Terraform import existing resource", tags: ["terraform"], cmd: `terraform import aws_instance.web i-0abc123def456\nterraform state show aws_instance.web` },
  { id: "tf-plan-out", task: "Terraform plan to file", tags: ["terraform", "ci"], cmd: `terraform init\nterraform plan -out=tfplan\nterraform apply tfplan` },
  { id: "nginx-502-timeouts", task: "Nginx proxy_pass + timeout fix for 502", tags: ["nginx", "debug"], cmd: `location / {\n  proxy_pass http://backend:8080;\n  proxy_connect_timeout 60s;\n  proxy_send_timeout 60s;\n  proxy_read_timeout 60s;\n  proxy_set_header Host $host;\n  proxy_set_header X-Real-IP $remote_addr;\n}\nsudo nginx -t && sudo systemctl reload nginx` },
  { id: "nginx-error-log", task: "Tail nginx error log", tags: ["nginx", "debug"], cmd: `sudo tail -f /var/log/nginx/error.log\nsudo nginx -t` },
  { id: "docker-prune", task: "Docker cleanup disk space", tags: ["docker", "debug"], destructive: true, destructiveNote: "Removes unused images and volumes cluster-wide. Run in staging first — can break cached builds.", cmd: `docker system df\ndocker system prune -a --volumes\n# careful: removes unused images` },
  { id: "docker-logs-follow", task: "Follow container logs", tags: ["docker", "debug"], cmd: `docker logs -f <container>\ndocker inspect <container> --format='{{.State.ExitCode}}'` },
  { id: "k8s-crash-logs", task: "Logs from crashed pod", tags: ["k8s", "debug"], cmd: `kubectl logs <pod> -n <ns> --previous\nkubectl describe pod <pod> -n <ns>\nkubectl get events -n <ns> --sort-by='.lastTimestamp'` },
  { id: "k8s-image-pull", task: "Diagnose ImagePullBackOff", tags: ["k8s", "debug"], cmd: `kubectl describe pod <pod> -n <ns> | grep -A5 Events\nkubectl get secret -n <ns>\n# ensure imagePullSecrets if private registry` },
  { id: "k8s-rollout-undo", task: "Rollback deployment", tags: ["k8s"], cmd: `kubectl rollout history deploy/<name> -n <ns>\nkubectl rollout undo deploy/<name> -n <ns>\nkubectl rollout status deploy/<name> -n <ns>` },
  { id: "k8s-drain-node", task: "Safely drain node", tags: ["k8s"], destructive: true, destructiveNote: "Evicts all pods from the node. Run in staging first — causes workload disruption in prod.", cmd: `kubectl cordon <node>\nkubectl drain <node> --ignore-daemonsets --delete-emptydir-data\nkubectl uncordon <node>` },
  { id: "k8s-top", task: "Pod CPU/memory usage", tags: ["k8s", "debug"], cmd: `kubectl top nodes\nkubectl top pods -A --sort-by=memory` },
  { id: "vault-unseal", task: "Unseal Vault", tags: ["debug"], cmd: `vault status\nvault operator unseal\n# repeat until Sealed: false` },
  { id: "gha-oidc-aws", task: "GHA OIDC to AWS (workflow snippet)", tags: ["ci", "aws"], cmd: `permissions:\n  id-token: write\n  contents: read\nsteps:\n  - uses: aws-actions/configure-aws-credentials@v4\n    with:\n      role-to-assume: arn:aws:iam::123:role/GithubActionsRole\n      aws-region: us-east-1` },
  { id: "gha-docker-push", task: "GHA build and push image", tags: ["ci", "docker"], cmd: `- uses: docker/login-action@v3\n  with:\n    registry: ghcr.io\n    username: \${{ github.actor }}\n    password: \${{ secrets.GITHUB_TOKEN }}\n- uses: docker/build-push-action@v6\n  with:\n    push: true\n    tags: ghcr.io/org/app:\${{ github.sha }}` },
  { id: "gha-kube-deploy", task: "GHA kubectl apply", tags: ["ci", "k8s"], cmd: `- uses: azure/setup-kubectl@v4\n- run: kubectl apply -f k8s/\n  env:\n    KUBECONFIG: \${{ secrets.KUBECONFIG_B64 }}  # base64-encoded` },
  { id: "bitbucket-docker-svc", task: "Bitbucket Pipelines Docker service", tags: ["ci", "docker"], cmd: `definitions:\n  services:\n    docker:\n      memory: 2048\npipelines:\n  default:\n    - step:\n        services:\n          - docker\n        script:\n          - docker build -t myapp .\n          - docker push myapp` },
  { id: "git-undo-commit", task: "Revert last commit (safe)", tags: ["git"], cmd: `git revert HEAD\ngit push origin main` },
  { id: "git-stash-pop", task: "Restore stashed work", tags: ["git"], cmd: `git stash list\ngit stash pop` },
  { id: "certbot-renew", task: "Renew Let's Encrypt cert", tags: ["nginx"], cmd: `sudo certbot renew --dry-run\nsudo certbot renew\nsudo systemctl reload nginx` },
  { id: "journalctl-service", task: "Follow systemd service logs", tags: ["debug"], cmd: `sudo journalctl -u <service> -f --since "1 hour ago"\nsudo systemctl status <service>` },
  { id: "disk-full", task: "Find what's using disk", tags: ["debug"], cmd: `df -h\ndu -sh /* 2>/dev/null | sort -hr | head -20\nsudo journalctl --vacuum-time=7d` },
  { id: "k8s-cert-expiry", task: "Check ingress TLS cert expiry", tags: ["k8s", "nginx", "debug"], cmd: `kubectl get certificate -A\nkubectl describe certificate <name> -n <ns>\necho | openssl s_client -connect app.example.com:443 2>/dev/null | openssl x509 -noout -dates` },
  { id: "k8s-ingress-describe", task: "Debug ingress backend", tags: ["k8s", "debug"], cmd: `kubectl describe ingress <name> -n <ns>\nkubectl get endpoints -n <ns>\nkubectl logs -n ingress-nginx -l app.kubernetes.io/name=ingress-nginx --tail=50` },
  { id: "compose-up-build", task: "Compose up with rebuild", tags: ["docker"], cmd: `docker compose up -d --build\ndocker compose ps\ndocker compose logs -f <service>` },
  { id: "minikube-load-image", task: "Load local image into minikube", tags: ["docker", "k8s"], cmd: `docker build -t myapp:local .\nminikube image load myapp:local\n# set imagePullPolicy: IfNotPresent in deployment` },
  { id: "kubectl-context", task: "Switch kube context", tags: ["k8s"], cmd: `kubectl config get-contexts\nkubectl config use-context <context>\nkubectl cluster-info` },
  { id: "tf-state-list", task: "List terraform state resources", tags: ["terraform", "debug"], cmd: `terraform state list\nterraform state show aws_instance.web\nterraform refresh` },
  { id: "pipeline-docker-auth", task: "Fix CI docker push 401", tags: ["ci", "docker", "debug"], cmd: `# Verify registry login in CI before push\ndocker login registry.example.com -u $CI_USER -p $CI_TOKEN\n# K8s: create docker-registry secret\nkubectl create secret docker-registry regcred --docker-server=... --docker-username=... --docker-password=... -n <ns>` },
  { id: "k8s-exec-shell", task: "Shell into running pod", tags: ["k8s", "debug"], cmd: `kubectl exec -it <pod> -n <ns> -- /bin/sh\n# or -c <container> if multi-container` },
  { id: "k8s-delete-evicted", task: "Clean evicted pods", tags: ["k8s", "debug"], destructive: true, destructiveNote: "Deletes Failed pods cluster-wide. Verify they are evicted junk, not debugging evidence.", cmd: `kubectl get pods -A | grep Evicted\nkubectl delete pods -A --field-selector=status.phase=Failed` },
  { id: "aws-logs-tail", task: "Tail CloudWatch logs", tags: ["aws", "debug"], cmd: `aws logs tail /aws/lambda/my-function --follow --since 1h\naws logs describe-log-groups --log-group-name-prefix /ecs/` },
  { id: "haproxy-stats", task: "HAProxy backend status", tags: ["debug"], cmd: `echo "show stat" | socat stdio /var/run/haproxy/admin.sock\ncurl -I http://backend:port` },
  { id: "redis-cli-ping", task: "Test Redis connectivity", tags: ["debug"], cmd: `redis-cli -h <host> -p 6379 ping\nredis-cli -h <host> INFO server` },
  { id: "postgres-conn", task: "Test PostgreSQL connection", tags: ["debug"], cmd: `psql -h <host> -U <user> -d <db> -c "SELECT 1"\npg_isready -h <host> -p 5432` },
  { id: "curl-headers", task: "Check HTTP response headers", tags: ["debug", "nginx"], cmd: `curl -I https://app.example.com\ncurl -v http://localhost:8080/health 2>&1 | head -30` },
  { id: "k8s-describe-node", task: "Node NotReady / pressure", tags: ["k8s", "debug"], cmd: `kubectl describe node <node>\nkubectl get events -A --field-selector involvedObject.kind=Node\n# check DiskPressure, MemoryPressure, PIDPressure` },
  { id: "tf-workspace", task: "Switch terraform workspace", tags: ["terraform"], cmd: `terraform workspace list\nterraform workspace select prod\nterraform plan` },
  { id: "gitlab-runner-tags", task: "Fix GitLab runner tag mismatch", tags: ["ci", "debug"], cmd: `# .gitlab-ci.yml tags must match runner\n# Settings → CI/CD → Runners → note tags\n# tags: [docker, aws]` },
  { id: "unused-ebs", task: "Find unattached EBS volumes", tags: ["aws", "finops"], destructive: true, destructiveNote: "Delete only after snapshot. Run in staging account first.", cmd: `aws ec2 describe-volumes --filters Name=status,Values=available --query 'Volumes[*].[VolumeId,Size,CreateTime]' --output table\n# delete after snapshot:\n# aws ec2 delete-volume --volume-id vol-xxx` },
  { id: "old-amis", task: "List old AMIs you own", tags: ["aws", "finops"], destructive: true, destructiveNote: "Deregister only AMIs not referenced by launch templates. Run in staging first.", cmd: `aws ec2 describe-images --owners self --query 'Images | sort_by(@, &CreationDate)[*].[ImageId,Name,CreationDate]' --output table\n# deregister unused:\n# aws ec2 deregister-image --image-id ami-xxx` },
  { id: "idle-elb", task: "Find load balancers with no targets", tags: ["aws", "finops"], cmd: `for lb in $(aws elbv2 describe-load-balancers --query 'LoadBalancers[*].LoadBalancerArn' --output text); do\n  echo "$lb"\n  aws elbv2 describe-target-health --target-group-arn $(aws elbv2 describe-target-groups --load-balancer-arn $lb --query 'TargetGroups[0].TargetGroupArn' --output text)\ndone` },
  { id: "k8s-no-requests", task: "Audit pods missing resource requests", tags: ["k8s", "finops"], cmd: `kubectl get pods -A -o json | jq -r '.items[] | select(.spec.containers[].resources.requests == null) | "\\(.metadata.namespace)/\\(.metadata.name)"'` },
  { id: "k8s-over-provisioned", task: "Compare requests vs actual usage", tags: ["k8s", "finops", "debug"], cmd: `kubectl top pods -A --sort-by=cpu\n# vs kubectl get pods -A -o custom-columns=NS:.metadata.namespace,NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu` },
  { id: "trivy-scan-image", task: "Trivy scan image before deploy", tags: ["docker", "finops", "ci"], cmd: `trivy image --severity HIGH,CRITICAL myapp:tag\ntrivy image --exit-code 1 --severity CRITICAL myapp:tag` },
  { id: "docker-image-size", task: "Check Docker image size", tags: ["docker", "finops"], cmd: `docker images myapp --format "{{.Repository}}:{{.Tag}} {{.Size}}"\ndocker history myapp:latest --no-trunc | head -20` },
  { id: "aws-cost-s3", task: "S3 buckets by size (top)", tags: ["aws", "finops"], cmd: `# requires s3 ls + cloudwatch or aws s3api list-objects-v2\naws s3 ls\n# enable S3 Storage Lens or Cost Explorer for detail` },
  { id: "stop-idle-ec2", task: "List long-running EC2 instances", tags: ["aws", "finops"], cmd: `aws ec2 describe-instances --filters Name=instance-state-name,Values=running --query 'Reservations[*].Instances[*].[InstanceId,InstanceType,LaunchTime,Tags[?Key==\`Name\`].Value|[0]]' --output table` },
  { id: "finops-rightsize", task: "CloudWatch CPU avg (right-sizing hint)", tags: ["aws", "finops"], cmd: `aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name CPUUtilization --dimensions Name=InstanceId,Value=i-xxx --start-time $(date -u -v-7d +%Y-%m-%dT%H:%M:%S) --end-time $(date -u +%Y-%m-%dT%H:%M:%S) --period 86400 --statistics Average` },
  { id: "promql-error-rate", task: "PromQL: HTTP 5xx error rate", tags: ["observe", "k8s"], cmd: `# 5xx rate / total rate\nsum(rate(http_requests_total{status=~"5.."}[5m]))\n/\nsum(rate(http_requests_total[5m]))\n\n# by ingress\nsum by (ingress) (rate(nginx_ingress_controller_requests{status=~"5.."}[5m]))` },
  { id: "promql-pod-restarts", task: "PromQL: pod restart rate", tags: ["observe", "k8s"], cmd: `sum by (namespace, pod) (increase(kube_pod_container_status_restarts_total[1h])) > 3\n\n# top restarters\n topk(10, sum by (pod, namespace) (kube_pod_container_status_restarts_total))` },
  { id: "promql-latency-p99", task: "PromQL: P99 latency", tags: ["observe"], cmd: `histogram_quantile(0.99,\n  sum by (le) (rate(http_request_duration_seconds_bucket[5m]))\n)\n\n# ingress latency\nhistogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))` },
  { id: "promql-disk-usage", task: "PromQL: node disk usage %", tags: ["observe", "k8s"], cmd: `100 - (\n  avg by (instance) (node_filesystem_avail_bytes{mountpoint="/"}) /\n  avg by (instance) (node_filesystem_size_bytes{mountpoint="/"}) * 100\n)` },
  { id: "promql-cert-expiry", task: "PromQL: cert expiry days left", tags: ["observe", "k8s"], cmd: `(certmanager_certificate_expiration_timestamp_seconds - time()) / 86400 < 14\n\n# alert when < 7 days\n(certmanager_certificate_expiration_timestamp_seconds - time()) / 86400` },
  { id: "logql-errors", task: "LogQL: error lines last 15m", tags: ["observe"], cmd: `{namespace="apps"} |= "error" or |= "ERROR" or |= "panic"\n| json\n| line_format "{{.pod}} {{.message}}"\n\n# rate of error log lines\nsum(rate({namespace="apps"} |= "error" [5m])) by (pod)` },
  { id: "cloudwatch-errors", task: "CloudWatch Insights: 5xx / errors", tags: ["observe", "aws"], cmd: `fields @timestamp, @message\n| filter @message like /(?i)(error|5\\d\\d|exception)/\n| sort @timestamp desc\n| limit 100\n\n# EKS container logs\nfields @timestamp, kubernetes.pod_name, @message\n| filter @message like /ERROR/\n| stats count() by kubernetes.pod_name` },
  { id: "gke-kubeconfig", task: "GKE kubeconfig merge", tags: ["gcp", "k8s"], cmd: `gcloud container clusters get-credentials my-cluster --region us-central1 --project my-project\nkubectl config current-context\nkubectl get nodes` },
  { id: "gcp-artifact-registry", task: "GCP Artifact Registry docker push", tags: ["gcp", "docker", "ci"], cmd: `gcloud auth configure-docker us-central1-docker.pkg.dev\ndocker tag myapp:latest us-central1-docker.pkg.dev/my-project/my-repo/myapp:tag\ndocker push us-central1-docker.pkg.dev/my-project/my-repo/myapp:tag` },
  { id: "gke-workload-identity", task: "GKE Workload Identity (KSA → GSA)", tags: ["gcp", "k8s", "ci"], cmd: `# Bind K8s SA to GCP SA\ngcloud iam service-accounts add-iam-policy-binding GSA@PROJECT.iam.gserviceaccount.com \\\n  --role roles/iam.workloadIdentityUser \\\n  --member "serviceAccount:PROJECT.svc.id.goog[NAMESPACE/KSA]"\n\n# Deployment annotation:\n# iam.gke.io/gcp-service-account: GSA@PROJECT.iam.gserviceaccount.com` },
  { id: "aks-kubeconfig", task: "AKS kubeconfig merge", tags: ["azure", "k8s"], cmd: `az aks get-credentials --resource-group my-rg --name my-aks\nkubectl config current-context\nkubectl get nodes` },
  { id: "acr-login", task: "Azure ACR docker login + push", tags: ["azure", "docker", "ci"], cmd: `az acr login --name myregistry\ndocker tag myapp:latest myregistry.azurecr.io/myapp:tag\ndocker push myregistry.azurecr.io/myapp:tag` },
  { id: "azure-federated-creds", task: "Azure federated creds for GitHub OIDC", tags: ["azure", "ci"], cmd: `az ad app federated-credential create \\\n  --id $APP_ID \\\n  --parameters '{\n    "name": "github-main",\n    "issuer": "https://token.actions.githubusercontent.com",\n    "subject": "repo:org/repo:ref:refs/heads/main",\n    "audiences": ["api://AzureADTokenExchange"]\n  }'\n# then azure/login@v2 with client-id, tenant-id, subscription-id` },
  { id: "pg-dump-backup", task: "PostgreSQL logical backup (pg_dump)", tags: ["backup"], cmd: `pg_dump -h <host> -U <user> -d <db> -Fc -f backup-$(date +%F).dump\n# custom format (-Fc) supports parallel restore\naws s3 cp backup-$(date +%F).dump s3://my-backups/postgres/` },
  { id: "pg-restore", task: "PostgreSQL restore from pg_dump", tags: ["backup"], destructive: true, destructiveNote: "Overwrites target database. Restore to empty DB or staging first.", cmd: `createdb -h <host> -U <user> restore_test\npg_restore -h <host> -U <user> -d restore_test -c backup-2026-06-21.dump\npsql -h <host> -U <user> -d restore_test -c "SELECT count(*) FROM users;"` },
  { id: "mysql-dump-backup", task: "MySQL mysqldump backup", tags: ["backup"], cmd: `mysqldump -h <host> -u <user> -p --single-transaction --routines <db> > backup-$(date +%F).sql\ngzip backup-$(date +%F).sql\naws s3 cp backup-$(date +%F).sql.gz s3://my-backups/mysql/` },
  { id: "mysql-restore", task: "MySQL restore from dump", tags: ["backup"], destructive: true, destructiveNote: "Drops and recreates data in target DB. Use staging first.", cmd: `gunzip -c backup-2026-06-21.sql.gz | mysql -h <host> -u <user> -p <db>\nmysql -h <host> -u <user> -p -e "SELECT COUNT(*) FROM users;" <db>` },
  { id: "mongo-dump-backup", task: "MongoDB mongodump archive", tags: ["backup"], cmd: `mongodump --uri="mongodb://user:pass@host:27017/app" --archive=backup-$(date +%F).gz --gzip\naws s3 cp backup-$(date +%F).gz s3://my-backups/mongo/` },
  { id: "mongo-restore", task: "MongoDB restore from archive", tags: ["backup"], destructive: true, destructiveNote: "Restores into existing collections. Test on empty DB first.", cmd: `mongorestore --uri="mongodb://host:27017" --archive=backup-2026-06-21.gz --gzip --drop\nmongosh --eval "db.users.countDocuments()"` },
  { id: "redis-rdb-backup", task: "Redis RDB snapshot (BGSAVE)", tags: ["backup", "redis"], cmd: `redis-cli -h <host> BGSAVE\nredis-cli -h <host> LASTSAVE\n# copy /var/lib/redis/dump.rdb to backup storage\nscp redis-host:/var/lib/redis/dump.rdb ./backup-$(date +%F).rdb` },
  { id: "redis-restore-rdb", task: "Redis restore RDB file", tags: ["backup", "redis"], destructive: true, destructiveNote: "Stop Redis, replace dump.rdb, restart — data loss if wrong file.", cmd: `sudo systemctl stop redis\nsudo cp backup-2026-06-21.rdb /var/lib/redis/dump.rdb\nsudo chown redis:redis /var/lib/redis/dump.rdb\nsudo systemctl start redis\nredis-cli ping` },
  { id: "velero-backup-ns", task: "Velero backup namespace", tags: ["backup", "k8s", "aws"], cmd: `velero backup create apps-$(date +%F) --include-namespaces apps --wait\nvelero backup describe apps-$(date +%F)\nvelero backup logs apps-$(date +%F)` },
  { id: "velero-restore", task: "Velero restore from backup", tags: ["backup", "k8s"], destructive: true, destructiveNote: "Restores resources into cluster — use --namespace-mappings to staging NS first.", cmd: `velero restore create restore-$(date +%F) --from-backup apps-2026-06-21 --wait\nvelero restore describe restore-$(date +%F)\nkubectl get all -n apps` },
  { id: "etcd-snapshot", task: "etcd snapshot (control plane)", tags: ["backup", "k8s"], cmd: `ETCDCTL_API=3 etcdctl snapshot save /backup/etcd-$(date +%F).db \\\n  --endpoints=https://127.0.0.1:2379 \\\n  --cacert=/etc/kubernetes/pki/etcd/ca.crt \\\n  --cert=/etc/kubernetes/pki/etcd/server.crt \\\n  --key=/etc/kubernetes/pki/etcd/server.key\netcdctl snapshot status /backup/etcd-$(date +%F).db` },
  { id: "etcd-restore-snapshot", task: "etcd restore snapshot", tags: ["backup", "k8s"], destructive: true, destructiveNote: "Cluster-wide disaster recovery only — follow vendor runbook; wrong step bricks cluster.", cmd: `# STOP API server + etcd on all nodes first — follow your K8s distro docs\nETCDCTL_API=3 etcdctl snapshot restore /backup/etcd-2026-06-21.db \\\n  --data-dir=/var/lib/etcd-restore\n# then reconfigure etcd to use restored data dir` },
  { id: "tf-state-pull", task: "Terraform state backup (pull local copy)", tags: ["backup", "terraform"], cmd: `terraform state pull > terraform.tfstate.backup-$(date +%F).json\n# remote backend: enable S3 versioning on state bucket\naws s3api list-object-versions --bucket my-tf-state --prefix prod/terraform.tfstate` },
  { id: "tf-state-version-restore", task: "Restore Terraform state from S3 version", tags: ["backup", "terraform", "aws"], destructive: true, destructiveNote: "Wrong state version can destroy infra on next apply. Coordinate with team.", cmd: `aws s3api list-object-versions --bucket my-tf-state --prefix prod/terraform.tfstate\naws s3api get-object --bucket my-tf-state --key prod/terraform.tfstate --version-id <VERSION_ID> terraform.tfstate\nterraform state push terraform.tfstate  # only if intentional` },
  { id: "rds-snapshot", task: "AWS RDS manual snapshot", tags: ["backup", "aws"], cmd: `aws rds create-db-snapshot --db-instance-identifier mydb --db-snapshot-identifier mydb-pre-upgrade-$(date +%F)\naws rds wait db-snapshot-available --db-snapshot-identifier mydb-pre-upgrade-$(date +%F)\naws rds describe-db-snapshots --db-instance-identifier mydb` },
  { id: "rds-restore-snapshot", task: "AWS RDS restore snapshot to new instance", tags: ["backup", "aws"], cmd: `aws rds restore-db-instance-from-db-snapshot \\\n  --db-instance-identifier mydb-restore-test \\\n  --db-snapshot-identifier mydb-pre-upgrade-2026-06-21\n# verify app against restore-test endpoint before cutover` },
  { id: "s3-sync-backup", task: "Sync directory to S3 (config backup)", tags: ["backup", "aws"], cmd: `aws s3 sync /etc/nginx s3://my-backups/nginx/$(hostname)/ --exclude "*.tmp"\naws s3 sync s3://my-backups/nginx/$(hostname)/ ./restore-test/ --dryrun` },
  { id: "s3-sync-restore", task: "Restore files from S3 sync", tags: ["backup", "aws"], destructive: true, destructiveNote: "Overwrites local files. Dry-run first; restore to temp dir.", cmd: `aws s3 sync s3://my-backups/nginx/myhost/ /tmp/nginx-restore/ --dryrun\naws s3 sync s3://my-backups/nginx/myhost/ /tmp/nginx-restore/\ndiff -r /etc/nginx /tmp/nginx-restore/` },
  { id: "dns-check", task: "DNS lookup debug (dig + nslookup)", tags: ["debug", "nginx"], cmd: `dig app.example.com +short\ndig app.example.com ANY\nnslookup app.example.com\n# compare to ingress LB: kubectl get ingress -n apps` },
  { id: "port-check", task: "Test TCP port open (nc / curl)", tags: ["debug"], cmd: `nc -zv backend.example.com 443\ncurl -v telnet://backend:8080\nss -tlnp | grep 8080` },
  { id: "systemd-restart-cluster", task: "Restart service safely (systemd)", tags: ["debug"], cmd: `sudo systemctl status <service>\nsudo systemctl restart <service>\nsudo journalctl -u <service> -n 50 --no-pager\nsudo systemctl is-active <service>` },
  { id: "openssl-cert-check", task: "Check TLS cert expiry from CLI", tags: ["debug", "nginx", "backup"], cmd: `echo | openssl s_client -connect app.example.com:443 -servername app.example.com 2>/dev/null | openssl x509 -noout -dates -subject\n# days left:\necho | openssl s_client -connect app.example.com:443 2>/dev/null | openssl x509 -noout -checkend 604800` },
  { id: "cron-backup-script", task: "Cron backup script template", tags: ["backup"], cmd: `#!/bin/bash\n# /usr/local/bin/backup.sh — install via cron: 0 2 * * * /usr/local/bin/backup.sh\nset -euo pipefail\nBACKUP_DIR=/var/backups\nDATE=$(date +%F)\npg_dump -U app appdb | gzip > "$BACKUP_DIR/appdb-$DATE.sql.gz"\nfind "$BACKUP_DIR" -name 'appdb-*.sql.gz' -mtime +14 -delete\naws s3 cp "$BACKUP_DIR/appdb-$DATE.sql.gz" s3://my-backups/cron/` },
  { id: "pg-rotate-user", task: "PostgreSQL rotate app user password", tags: ["k8s", "backup"], cmd: `# 1. Create parallel user\nCREATE USER app_v2 WITH PASSWORD 'new-secret';\nGRANT ALL ON DATABASE appdb TO app_v2;\nGRANT ALL ON ALL TABLES IN SCHEMA public TO app_v2;\n# 2. Update K8s secret + rollout restart\nkubectl create secret generic db-creds --from-literal=password=new-secret -n apps --dry-run=client -o yaml | kubectl apply -f -\nkubectl rollout restart deploy/myapp -n apps` },
  { id: "k8s-secret-update-rollout", task: "Update K8s secret + rolling restart", tags: ["k8s", "ci"], cmd: `kubectl create secret generic app-secrets \\\n  --from-literal=API_KEY=new-key \\\n  -n apps --dry-run=client -o yaml | kubectl apply -f -\nkubectl rollout restart deploy/myapp -n apps\nkubectl rollout status deploy/myapp -n apps` },
  { id: "irsa-verify-pod", task: "Verify IRSA role from pod", tags: ["aws", "k8s"], cmd: `kubectl exec -it deploy/myapp -n apps -- env | grep AWS\nkubectl exec -it deploy/myapp -n apps -- aws sts get-caller-identity\n# expect role ARN matching ServiceAccount annotation` },
  { id: "k8s-rollout-restart-sa", task: "Restart all pods using ServiceAccount", tags: ["k8s"], cmd: `# after SA annotation change\nkubectl rollout restart deploy -n apps\nkubectl get pods -n apps -o jsonpath='{range .items[*]}{.metadata.name}{" SA="}{.spec.serviceAccountName}{"\\n"}{end}'` },
  { id: "vault-kv-update", task: "Vault KV — write new secret version", tags: ["debug"], cmd: `vault kv put secret/apps/myapp db_password=new-secret api_key=new-key\nvault kv get secret/apps/myapp\n# External Secrets Operator syncs within refreshInterval` },
  { id: "cert-manager-http01", task: "cert-manager HTTP-01 ClusterIssuer", tags: ["k8s", "nginx"], cmd: `apiVersion: cert-manager.io/v1\nkind: ClusterIssuer\nmetadata:\n  name: letsencrypt-prod\nspec:\n  acme:\n    server: https://acme-v02.api.letsencrypt.org/directory\n    email: ops@example.com\n    privateKeySecretRef:\n      name: letsencrypt-prod\n    solvers:\n      - http01:\n          ingress:\n            class: nginx` },
  { id: "cert-manager-dns01", task: "cert-manager DNS-01 (Route53 wildcard)", tags: ["k8s", "aws"], cmd: `apiVersion: cert-manager.io/v1\nkind: ClusterIssuer\nmetadata:\n  name: letsencrypt-dns\nspec:\n  acme:\n    server: https://acme-v02.api.letsencrypt.org/directory\n    email: ops@example.com\n    privateKeySecretRef:\n      name: letsencrypt-dns\n    solvers:\n      - dns01:\n          route53:\n            region: us-east-1\n            hostedZoneID: Z123456\n# Certificate dnsNames: [example.com, '*.example.com']` },
  { id: "cert-internal-ca", task: "cert-manager self-signed CA Issuer", tags: ["k8s"], cmd: `apiVersion: cert-manager.io/v1\nkind: Issuer\nmetadata:\n  name: internal-ca\n  namespace: apps\nspec:\n  selfSigned: {}\n---\napiVersion: cert-manager.io/v1\nkind: Certificate\nmetadata:\n  name: internal-tls\n  namespace: apps\nspec:\n  secretName: internal-tls\n  issuerRef:\n    name: internal-ca\n  dnsNames:\n    - svc.apps.svc.cluster.local` },
  { id: "kube-context-diff", task: "Quick diff deploy images across contexts", tags: ["k8s", "debug"], cmd: `for ctx in staging prod; do\n  echo "=== $ctx ==="\n  kubectl --context=$ctx get deploy -n apps -o custom-columns=NAME:.metadata.name,IMAGE:.spec.template.spec.containers[0].image\ndone` },
  { id: "tf-workspace-list", task: "Terraform workspace compare workflow", tags: ["terraform"], cmd: `terraform workspace list\nterraform workspace select staging && terraform plan -no-color > /tmp/plan-staging.txt\nterraform workspace select prod && terraform plan -no-color > /tmp/plan-prod.txt\ndiff -u /tmp/plan-staging.txt /tmp/plan-prod.txt || true` },
  { id: "argocd-sync-status", task: "Argo CD — app status and sync", tags: ["k8s", "ci", "debug"], cmd: `argocd app list\nargocd app get <app> --refresh\nargocd app sync <app>\nargocd app diff <app>` },
  { id: "argocd-hard-refresh", task: "Argo CD — hard refresh stuck app", tags: ["k8s", "ci", "debug"], cmd: `argocd app get <app> --hard-refresh\nkubectl patch application <app> -n argocd --type merge -p '{"operation":{"initiatedBy":{"username":"admin"},"sync":{"revision":"HEAD"}}}'` },
  { id: "flux-reconcile", task: "Flux — force reconcile source/kustomization", tags: ["k8s", "ci", "debug"], cmd: `flux get sources git -A\nflux get kustomizations -A\nflux reconcile source git <name> -n flux-system\nflux reconcile kustomization <name> -n flux-system --with-source` },
  { id: "jenkins-kubectl", task: "Jenkins — kubectl deploy from pipeline", tags: ["ci", "k8s"], cmd: `pipeline {\n  agent any\n  stages {\n    stage('Deploy') {\n      steps {\n        withKubeConfig([credentialsId: 'kubeconfig']) {\n          sh 'kubectl apply -f k8s/'\n          sh 'kubectl rollout status deploy/myapp -n apps'\n        }\n      }\n    }\n  }\n}` },
  { id: "k8s-probe-fix", task: "Fix failing liveness/readiness probe", tags: ["k8s", "debug"], cmd: `# describe shows probe failures\nkubectl describe pod <pod> -n <ns> | grep -A3 Liveness\n# common fix — separate paths, longer initialDelaySeconds\nreadinessProbe:\n  httpGet:\n    path: /health\n    port: 8080\n  initialDelaySeconds: 15\n  periodSeconds: 10\nlivenessProbe:\n  httpGet:\n    path: /health\n    port: 8080\n  initialDelaySeconds: 30\n  failureThreshold: 3` },
  { id: "k8s-hpa-status", task: "Debug HPA not scaling", tags: ["k8s", "debug"], cmd: `kubectl get hpa -n <ns>\nkubectl describe hpa <name> -n <ns>\nkubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/<ns>/pods" | head\n# metrics-server must be running` },
  { id: "promql-cpu-throttle", task: "PromQL: CPU throttling rate", tags: ["observe", "k8s"], cmd: `sum by (pod, namespace) (rate(container_cpu_cfs_throttled_seconds_total[5m]))\n\n# top throttled\n topk(10, sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total[5m])))` },
  { id: "promql-pod-memory", task: "PromQL: pod memory vs limit", tags: ["observe", "k8s"], cmd: `sum by (pod, namespace) (container_memory_working_set_bytes)\n/\nsum by (pod, namespace) (kube_pod_container_resource_limits{resource="memory"}) * 100\n\n# OOM risk > 90%` },
  { id: "kubectl-auth-can-i", task: "RBAC — can I perform action?", tags: ["k8s", "debug"], cmd: `kubectl auth can-i create deployments -n apps\nkubectl auth can-i get secrets --as=system:serviceaccount:apps:default -n apps\nkubectl describe rolebinding -n apps` },
  { id: "es-cluster-health", task: "Elasticsearch cluster health", tags: ["observe", "debug"], cmd: `curl -s http://localhost:9200/_cluster/health?pretty\ncurl -s http://localhost:9200/_cat/indices?v\ncurl -s http://localhost:9200/_cat/shards?v | grep UNASSIGNED` },
  { id: "gitlab-ci-k8s-deploy", task: "GitLab CI — deploy to K8s", tags: ["ci", "k8s"], cmd: `deploy:\n  stage: deploy\n  image: bitnami/kubectl:latest\n  script:\n    - kubectl config use-context org/cluster\n    - kubectl apply -f k8s/\n    - kubectl rollout status deploy/myapp -n apps\n  only:\n    - main` },
  { id: "gha-github-pages", task: "GitHub Actions — deploy to GitHub Pages", tags: ["ci"], cmd: `name: Deploy Pages\non:\n  push:\n    branches: [main]\npermissions:\n  contents: read\n  pages: write\n  id-token: write\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/configure-pages@v5\n      - uses: actions/upload-pages-artifact@v3\n        with:\n          path: ./public\n      - uses: actions/deploy-pages@v4` },
  { id: "ssh-jump-host", task: "SSH ProxyJump to private host", tags: ["debug", "linux"], cmd: `ssh -J bastion@jump.example.com user@10.0.2.50\n# ~/.ssh/config:\n# Host private\n#   ProxyJump bastion@jump.example.com\n#   HostName 10.0.2.50\n#   User deploy` },
  { id: "fail2ban-ssh", task: "Fail2ban — protect SSH", tags: ["linux", "debug"], cmd: `sudo apt install fail2ban\nsudo tee /etc/fail2ban/jail.local <<'EOF'\n[sshd]\nenabled = true\nport = ssh\nmaxretry = 5\nbantime = 3600\nEOF\nsudo systemctl enable --now fail2ban\nsudo fail2ban-client status sshd` },
  { id: "chrony-sync", task: "Chrony NTP sync check", tags: ["linux", "debug"], cmd: `chronyc tracking\nchronyc sources -v\ntimedatectl status` },
];

export function getSnippetSearchItems() {
  return snippets.map((s) => ({
    slug: s.id,
    name: s.task,
    description: s.cmd.split("\n")[0],
    icon: snippetTags.find((t) => s.tags.includes(t.id))?.icon ?? "📋",
    keywords: [...s.tags, s.task, ...(s.tool ? [s.tool] : []), "snippet", "command"],
  }));
}

export function filterSnippets(tag?: string, query?: string) {
  let list = snippets;
  if (tag) list = list.filter((s) => s.tags.includes(tag));
  if (query?.trim()) {
    const q = query.toLowerCase();
    list = list.filter(
      (s) => s.task.toLowerCase().includes(q) || s.cmd.toLowerCase().includes(q) || s.tags.some((t) => t.includes(q))
    );
  }
  return list;
}
